backend:
  name: git-gateway
  branch: master

media_folder: static/img
public_folder: /img

collections:
  - name: "Projects"
    label: "Projects"
    folder: "src/pages/projects"
    create: true
    fields:
       - {label: "Language", name: "language", widget: "string", default: "en"}
       - {label: "Template Key", name: "templateKey", widget: "hidden", default: "project"}
       - {label: "Path", name: "path", widget: "string", default: "/project-name"}
       - {label: "Project number", name: "order", widget: "number"}
       - {label: "Thumbnail", name: "thumbnail", widget: "image"}
       - {label: "Title", name: "title", widget: "string"}
       - {label: "Media", name: "media", widget: "string"}
       - {label: "Year", name: "year", widget: "number"}
       - {label: "Location", name: "location", widget: "string"}
       - {label: "Duration", name: "duration", widget: "string", required: false}
       - {label: "Description", name: "description", widget: "text"}
       - {label: "Performers", name: "performers", widget: "text"}
       - {label: "Documentation", name: "documentation", widget: "string"}
       - {label: "Extra credits 1", name: "Extra1", widget: "string", required: false}
       - {label: "Extra credits 2", name: "Extra2", widget: "string", required: false}
       - {label: "Body", name: "body", widget: "markdown"}
  - name: "Projects_de"
    label: "Projects_de"
    folder: "src/pages/projects/de"
    create: true
    fields:
       - {label: "Language", name: "language", widget: "string", default: "de"}
       - {label: "Template Key", name: "templateKey", widget: "hidden", default: "project"}
       - {label: "Path", name: "path", widget: "string", default: "/project-name"}
       - {label: "Project number", name: "order", widget: "number"}
       - {label: "Thumbnail", name: "thumbnail", widget: "image"}
       - {label: "Title", name: "title", widget: "string"}
       - {label: "Media", name: "media", widget: "string"}
       - {label: "Year", name: "year", widget: "number"}
       - {label: "Location", name: "location", widget: "string"}
       - {label: "Duration", name: "duration", widget: "string"}
       - {label: "Description", name: "description", widget: "text"}
       - {label: "Performers", name: "performers", widget: "text"}
       - {label: "Documentation", name: "documentation", widget: "string"}
       - {label: "Extra credits 1", name: "Extra1", widget: "string"}
       - {label: "Extra credits 2", name: "Extra2", widget: "string"}
       - {label: "Body", name: "body", widget: "markdown"}
  - name: "pages"
    label: "Pages"
    files:
      - file: "src/pages/Info/Info.md"
        label: "Info"
        name: "Info"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "info-page"}
          - {label: "Path", name: "path", widget: "string"}
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Body", name: "body", widget: "markdown"}
      - file: "src/pages/Contact/Contact.md"
        label: "Contact"
        name: "Contact"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "contact-page"}
          - {label: "Path", name: "path", widget: "string"}
          - {label: "Title", name: "title", widget: "string"}
          - {label: "E-mail", name: "email", widget: "string"}
          - {label: "Body", name: "body", widget: "markdown"}
  - name: "pages_de"
    label: "Pages_de"
    files:
      - file: "src/pages/Info/de/de_Info.md"
        label: "Info_de"
        name: "Info_de"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "info-page"}
          - {label: "Path", name: "path", widget: "string"}
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Body", name: "body", widget: "markdown"}
      - file: "src/pages/Contact/de/Kontakt.md"
        label: "Contact_de"
        name: "Contact_de"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "contact-page"}
          - {label: "Path", name: "path", widget: "string"}
          - {label: "Title", name: "title", widget: "string"}
          - {label: "E-mail", name: "email", widget: "string"}
          - {label: "Body", name: "body", widget: "markdown"}
